version: '3.1'

services:
  cmc_bot:
    build:
      context: .
    restart: always
    env_file:
      - ./.env
    environment:
       - BOT_PUBLIC_PORT=8081
#      - TELEGRAM_API_ID="<api-id>"
#      - TELEGRAM_API_ID=${POSTGRES_USER}
#      - TELEGRAM_API_HASH="<api-hash>"
    ports:
      - "8081:8081"
    volumes:
      - .:/cmc_bot
    command: >
      sh -c "python bot.py"
#    depends_on:
#       - postgres
#       - redis
    networks:
      - cmc_cmc_network

#volumes:
#  postgres_data:
#    driver: local

networks:
  cmc_cmc_network:
    external: true
